[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
cache_path = "cache"

# Solidity compiler settings
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = true

# Gas settings
gas_limit = 30_000_000
gas_price = 1_000_000_000  # 1 gwei

# Testing settings
fuzz = { runs = 1000 }
invariant = { runs = 256, depth = 15 }

# Remappings for common DeFi protocols
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@chainlink/=lib/chainlink/",
    "@chainlink-brownie-contracts/=lib/chainlink-brownie-contracts/",
    "@uniswap/=lib/uniswap/",
    "@aave/=lib/aave/",
    "forge-std/=lib/forge-std/src/",
]

# Network settings
[rpc_endpoints]
mantle_sepolia = "https://mantle-sepolia.g.alchemy.com/v2/jdM50XRTIYZjoASnttLZ9Wn00jVbOxSB"





# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
